### ISSUE TITLE
Cannot run client in Node 17

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/SOMEF-Vider#15]
Hello, 
I have run into an issue when running the client. See stacktrace below:
```
dgarijo@pop-os:~/Documents/GitHub/SOMEF-Vider/client$ sudo npm run serve

> client@0.1.0 serve /home/dgarijo/Documents/GitHub/SOMEF-Vider/client
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/5 modules 3 active ...ents/GitHub/SOMEF-Vider/client/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-14T16_35_15_008Z-debug.log
```
The log shows:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'serve' ]
2 info using npm@6.14.8
3 info using node@v17.2.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle client@0.1.0~preserve: client@0.1.0
6 info lifecycle client@0.1.0~serve: client@0.1.0
7 verbose lifecycle client@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~serve: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dgarijo/Documents/GitHub/SOMEF-Vider/client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle client@0.1.0~serve: CWD: /home/dgarijo/Documents/GitHub/SOMEF-Vider/client
10 silly lifecycle client@0.1.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle client@0.1.0~serve: Returned: code: 1  signal: null
12 info lifecycle client@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: client@0.1.0 serve: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:390:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:390:28)
13 verbose stack     at maybeClose (node:internal/child_process:1062:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
14 verbose pkgid client@0.1.0
15 verbose cwd /home/dgarijo/Documents/GitHub/SOMEF-Vider/client
16 verbose Linux 5.15.5-76051505-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
18 verbose node v17.2.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error client@0.1.0 serve: `vue-cli-service serve`
22 error Exit status 1
23 error 22 error Exit status 1
23 error Failed at the client@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
Failed at the client@0.1.0 serve script.
```
NPM version: 6.14.8
Commands run: `npm install`, `npm run serve`

NPM run build gives the same error

**Comment by dgarijo** [comment]
Node version: v17.2.0

**Comment by dgarijo** [comment]
Doesn't work for node 17. It seems to work for node 16

**Comment by Vitoriox** [comment]
Should work normally with node version 12.22.7
Version upgrade is in progress

**Comment by Vitoriox** [comment]
After testing, the client seems to run and build properly for versions:
 - NPM 8.1.2
 - Node 16.13.1

**Comment by dgarijo** [comment]
I think it should be compatible with Node versions > 16

**Comment by Vitoriox** [comment]
@dgarijo 
The client should run with node 16 because is the latest LTS version 
Node 17 won't be compatible with future developments, more info at https://nodejs.org/es/about/releases/

**Comment by dgarijo** [comment]
Very well
